eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://localhost:8761/eureka/
server:
  #当前服务端口号
  port: 8888
 
spring:
  application:
    #当前应用名称
    name: ict-gateway
zuul:
  routes:
    api-exam:
      path:/jm-user/**
      serviceId:jm-user
    api-question:
      path:/jm-fair/**
      serviceId:jm-fair
    api-common:
      path:/jm-borrow/**
      serviceId:jm-borrow
      
  host:
      connect-timeout-millis: 60000
      socket-timeout-millis: 60000
ribbon: 
  ReadTimeout: 60000 
  ConnectTimeout: 60000
hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 60000
 

 
 
 
